name: june_mobile_database_template
description: "create a mobile database model template for juneflow."
#publish_to: 'none'
repository: https://github.com/juneflow-songdo/june_mobile_database_template

version: 1.2.2

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  after_layout:
  bot_toast:
  device_preview:
  flutter:
    sdk: flutter
  flutter_screenutil:
  flutter_svg:
  flutter_zoom_drawer:
  gap:
  go_router:
  june:
  june_flow_util:
  keyboard_attachable:
  modal_bottom_sheet:
  styled_widget:
  sqflite: #@add
  flutter_secure_storage: #@add
  shared_preferences:
  path: #@add
  orange:
  path_provider: #@add

dev_dependencies:
  bot_toast_module:
  device_preview_module:
  flutter_lints:
  flutter_lints_module:
  flutter_test:
    sdk: flutter
  june_model: #@add
  june_usecase_template: #@add
  june_view:
  june_view_more:
  orange_module:
  screenutil_module:

flutter:
  assets:
    - assets/module/june_mobile_database_template/
  uses-material-design: true